apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-84-sno"
  namespace: "master-dell-84-sno"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-4-ocp49-2" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1F010CmS25bXcGEzLIoUgBtAITR51wP0sfeJcho7Bo6Pe6v54oSerVddJrvXwiq5Xrei98Ly2ySRZGo6efpNSTBSBg1FbrMhBqxxLUfAdF+UK19kNmRbD57ALqMUZ4EKW+2pnHv9JZVZ7DXzgbQ9DOb7PvqsYH/qWPXR9q1bCUP+vOvTQtZEakI7esbE4qHFXzoaevCW3lCdJwWMuM6CxD5tu+wN+XPJ1G9agXr367r9M/Frue/8BFNkXzp5GITTZ1h2dNn29X7UuG2bxrVPmCXRSMZ3pJmw8vq9bsDE13X5olpXemrzFErrxaTLrdKnAxVwcWdlOCzCI0aAW3bgZ"
  clusters:
  - clusterName: "master-dell-84-sno"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-84-sno"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-84-sno"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.45/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-84-sno-master-dell-84-sno-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:02:40"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:02:40"
            - name: ens1f0
              macAddress: 40:A6:B7:20:D4:B0 
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:02:40"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
               - name: ens1f0.2024
                 type: vlan
                 state: up
                 vlan:
                   base-iface: ens1f0
                   id: 2024
                 ipv4:
                   enabled: true
                   dhcp: false
                   address:
                   - ip: 9.37.195.90
                     prefix-length: 26
                     enabled: true 
                 ipv6:
                   enabled: false
               routes:
                 config:
                 - destination: 9.37.195.64/26
                   next-hop-address: 9.37.195.65
                   next-hop-interface: ens1f0.2024
                   table-id: 254
