---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-banashankari-supermicro00

commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  


resources:
  - 00-label-wait-job-banashankari-sno-6-pao.yaml

  - 00-pao-wait-job-banashankari-sno-6.yaml
#  - 01-mcp-ran-cu-banashankari-supermicro00.yaml
  - 02-pao-ran-cu-banashankari-supermicro00-profile0.yaml
