---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: banashankari-local-storage-supermicro00
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/banashankari-local-storage-supermicro00
          operator: Exists
  storageClassDevices:
    - storageClassName: "banashankari-local-storage-supermicro00"
      volumeMode: Filesystem
      fsType: xfs 
      devicePaths: 
        - /dev/autopart/lv_1
        - /dev/autopart/lv_2
        - /dev/autopart/lv_3
        - /dev/autopart/lv_4
        - /dev/autopart/lv_5
