---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-banashankari-supermicro00

resources:
  # SRIOV Configs
#  - 00-mcp-wait-job-banashankari-sno-6-sriov.yaml
  - 01-banashankari-sriov-namespace.yaml
  - 02-banashankari-sriov-node-policies.yaml
  - 03-banashankari-sriov-networks.yaml
  - 04-banashankari-local-storage-supermicro00.yaml
  - 05-banashankari-storageclass-supermicro00.yaml
 
