apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - namespace.yaml

  - hook-cluster-sub-role.yaml      # sitecoonfigs.ran.openshift.io
  - hook-cluster-sub-binding.yaml   # sitecoonfigs.ran.openshift.io

  - site-config-crd.yaml