apiVersion: v1
kind: Namespace
metadata:
  name: common
  labels:
    name: common
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub 
  labels:
    name: clusters-sub
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: policies-sub
  labels:
    name: policies-sub
    argocd.argoproj.io/managed-by: openshift-gitops