---
apiVersion: v1
kind: Namespace
metadata:
  name: xnf-5g-cu-dallas
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vran-serviceaccount
  namespace: xnf-5g-cu-dallas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vzw-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods", "authentication.k8s.io", "authorization.k8s.io", "secrets" ]
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vzw-rb
  namespace: xnf-5g-cu-dallas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vzw-role
subjects:
  - kind: ServiceAccount
    name: vran-serviceaccount
    namespace: xnf-5g-cu-dallas

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: xnf-5g-cu-dallas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: vran-serviceaccount
  namespace: xnf-5g-cu-dallas
