apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "std0-openshift-rdc"
  namespace: "std0-openshift-rdc"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-4-ocp49-1" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsMiPuxj4hjKQWMUgFJ/oYaD2hP2K3arnjn7vfNzfUMUO3bJoWL+OTNgTplMihFcotzDFylX/6vxdLZr1exFdvkMd6OQsWkkM/Uj2yfwIg4U37g9lXRtveY5FrUSkXTCnirFsyk8F95lDth+Z1ypSdZDJqCP7j/R5Klw3P0HTLIZdk+zh0tJ26hboezebDjDhKSJN0oSKEjdsLaQ5TvzgH+wqVawzxVgM7t2eas7nX3UuQrAmS2cmk3JVO/MxBBVkqjcSH0W8VgTtgRvCmC5hCPP/tGs2ReehCLEQVsoO9wefQhvNG53+/FVffdW4WJ4TFhb4gR9SKTN7jylf07ZeZ"
  clusters:
  - clusterName: "std0-openshift-rdc"
    clusterType: "standard"
    clusterProfile: "cu"
    numMasters: 3
    numWorkers: 2
    clusterLabels:
      common: true
      sites : "std0-openshift-rdc"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    apiVIP: 9.37.195.53
    ingressVIP: 9.37.195.54
    nodes:
       - hostName: "std0-openshift-rdcnode0"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "std0-openshift-rdc-std0-openshift-rdcnode0-bmh-secret"
         bootMACAddress: "E4:43:4B:F0:E3:00"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F0:E3:00"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F0:E3:00"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "std0-openshift-rdcnode1"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "std0-openshift-rdc-std0-openshift-rdcnode1-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:01:10"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:01:10"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:01:10"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "std0-openshift-rdcnode2"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.83/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "std0-openshift-rdc-std0-openshift-rdcnode2-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:A0:E0"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:A0:E0"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:A0:E0"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
