apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-node-42-sno"
  namespace: "master-node-42-sno"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.9.9-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkq+AkT6hzW0CRHFXxvlsGR696lTOc4ndbVuY493QbP576DrQyE7ZzUBZ9GGlNOGNkfggP5InCc6HF/OnetnwDOrDujoc74RGPovndhLddu8cI3xgTEWbYlsTKAmNXloIUMH4M9PhmBQnbNJWxJiOpQbXftzl+yoJues+1zzjgNJaFHc1UdUhJKIUxKbND9jCCF1yXAgKegDWebWoCrQCOEzkfXCNBCRU2A1QT/YWmAnQd9El/oX+JXKAlTignayIE63KjyPWH6L96nHeGswyT3P+0zGx1J6/t4EpuKy1YwzfU5NbW/AN/k7BvMFVBhhVb5U1BYjK2XRcdqpkJRA7z"
  clusters:
  - clusterName: "master-node-42-sno"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-node-42-sno"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/26
    nodes:
       - hostName: "master-node-42-sno"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-node-42-sno-master-node-42-sno-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
