---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: dallas-local-storage-dell00
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/dallas-local-storage-dell00
          operator: Exists
  storageClassDevices:
    - storageClassName: localstorage
      volumeMode: Filesystem
      fsType: xfs 
      devicePaths: 
        - /dev/autopart/lv_1
        - /dev/autopart/lv_2
        - /dev/autopart/lv_3
        - /dev/autopart/lv_4
        - /dev/autopart/lv_5
