---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: node-configs
 namespace: ibm-lab-std3
spec:
  syncPolicy: {}
  generators:
    - git:
        repoURL: https://github.com/kirankumarhn82/vran-manifests.git
        revision: main
        files:
        - path: "clusters/ibm-lab-std3.vran.ibm.com/sites/*/*/configs-*/config.json"
  template:
    metadata:
      name: '{{application-name}}'
      namespace: ibm-lab-std3
    spec:
      project: default
      source:
        repoURL: https://github.com/kirankumarhn82/vran-manifests.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{cluster-address}}'
      syncPolicy:
        automated:
          prune: false
          allowEmpty: true  
          selfHeal: true 
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: -1
        syncOptions:
        - Validate=false
        - CreateNamespace=true        