---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: phoenixqa8
  namespace: phoenixqa8
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: phoenixqa8
    version: v1beta1
  clusterName: phoenixqa8
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: phoenixqa8
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: phoenixqa8
  namespace: phoenixqa8
spec:
  apiVIP: 9.37.195.53
  ingressVIP: 9.37.195.54
  clusterDeploymentRef:
    name: phoenixqa8
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: "vran-ocp-v4.9.9-master-4-ocp49-2"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdaNJyE6TSS9WuC2uycJTcvZt0fuI16Q+SsE/m6BTHTtjw+N0fsSwFu4zEUM/k2AvAIazR8FZXRHt6cA/2aG7iZdDnTFTpDzNnA58HfKefYAQEsWtSTabZ08aw4Z62niAZ34+JsOdDGXOlnn6rvaRQ8UmzbD/Foi0qsqGEXG2RkBwqUUfPJh6iDJG1Y+ToRfuTk0oamMPY7KvsVelksNm/pM8UMxLDaWfaXcZLDAY8gYCKM+YfzDrpZjqMMbsUkjGYVynxU1+gZP8TJzktrwHZtm68MiLDTzHKpyNDlu0Sp6VgnrMMKcAWYvsgg/F7nWQsmC2svuZinwcbeOzOlpNj"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: phoenixqa8
  namespace: phoenixqa8
spec:
  clusterName: phoenixqa8
  clusterNamespace: phoenixqa8
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: phoenixqa8
  namespace: phoenixqa8
  
spec:
  clusterRef:
    name: phoenixqa8
    namespace: phoenixqa8
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: phoenixqa8
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdaNJyE6TSS9WuC2uycJTcvZt0fuI16Q+SsE/m6BTHTtjw+N0fsSwFu4zEUM/k2AvAIazR8FZXRHt6cA/2aG7iZdDnTFTpDzNnA58HfKefYAQEsWtSTabZ08aw4Z62niAZ34+JsOdDGXOlnn6rvaRQ8UmzbD/Foi0qsqGEXG2RkBwqUUfPJh6iDJG1Y+ToRfuTk0oamMPY7KvsVelksNm/pM8UMxLDaWfaXcZLDAY8gYCKM+YfzDrpZjqMMbsUkjGYVynxU1+gZP8TJzktrwHZtm68MiLDTzHKpyNDlu0Sp6VgnrMMKcAWYvsgg/F7nWQsmC2svuZinwcbeOzOlpNj"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-80-std"
  namespace: phoenixqa8
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa8"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa8-master-dell-80-std-bmh-secret
  bootMACAddress: E4:43:4B:F0:E3:00
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-81-std"
  namespace: phoenixqa8
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa8"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa8-master-dell-81-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:01:10
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-82-std"
  namespace: phoenixqa8
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa8"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa8-master-dell-82-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:A4:E0
  automatedCleaningMode: disabled
  online: true
---
