apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "dell-sam-poc"
  namespace: "dell-sam-poc"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.9.9-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6fbExU6L5EPIjty1iiQW9YQDiZRiBZUnzntAQ1unkitdtebvd+XRwFKYKFTR0FYE70s3jXwBtfI9P8EzlS5LGPXDJGGEox4VyOTGwNMtz66FqWO4XIU8Fw2u7km0Jo2ZBXcF6gKPLnXgB+HjKmHLFUHrGA3mXWlaiPYKS2MtoENTGpzfTWfNlu3nlX9HcOfyFyNwac3wuIQYCE3sOJXK8F/t+T88vQ+uTcNMTRLOJcLCllMz44mhl3HwRZbSksFRVYKTQISEyHueHpHB12rDSTrl5jMNicfUN1I+yJC77z1l5UnubndptuoTiUQPRgFqcGAALcdvC3an/h1zPHG33"
  clusters:
  - clusterName: "dell-sam-poc"
    clusterType: "sno"
    clusterProfile: "cu"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "dell-sam-poc"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "dell-sam-poc.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "dell-sam-poc-dell-sam-poc-bmh-secret"
         bootMACAddress: "E4:43:4B:F0:E3:00"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F0:E3:00"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F0:E3:00"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
