---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-bastion-ca
  namespace: openshift-config
data:
  domain.crt: |

    -----BEGIN CERTIFICATE-----
    MIIDqzCCApOgAwIBAgIUaLCDjXuMhv89C2dvPaR7xfUdTm0wDQYJKoZIhvcNAQEL
    BQAwZTELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQswCQYDVQQHDAJTWjENMAsG
    A1UECgwESUJNLjEtMCsGA1UEAwwkbWlycm9yLXJlZ2lzdHJ5LXZyYW5xYTEuZnly
    ZS5pYm0uY29tMB4XDTIyMDEwNjExNDIyNFoXDTMyMDEwNDExNDIyNFowZTELMAkG
    A1UEBhMCSU4xCzAJBgNVBAgMAktBMQswCQYDVQQHDAJTWjENMAsGA1UECgwESUJN
    LjEtMCsGA1UEAwwkbWlycm9yLXJlZ2lzdHJ5LXZyYW5xYTEuZnlyZS5pYm0uY29t
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAurgYm2q58hqUBlldmtLY
    /kTzYSB5GVFQVd7mGQ60hQYHNg516aSOpV9qfTHvqNC3wXIdhVrrRBDobR0hbfrX
    lbpVRYApgnGk1/Gq+8qgOi0EgeSSu9uJUWX8xQxemOaS5EmKOTZ+VGtcbfs2ZyPD
    gQ1lQ2ZPzxxTWJ+SXf8KFCaeLTD6MHF9E+ZS5ZsCiaDJK8YFZdZMBqFKtibywuOJ
    4lTWzipP76BZ3eAoyU4NzI0045mQ+puLMlsDfOIH8QpGB9GJkBZv26mX4kA4ESrn
    xP+7nHn23ocG1UycrlIdbZnRiTuS0onmRPzlL6wd+H9nJXKdEf5Mken9jYpIWK3C
    OwIDAQABo1MwUTAdBgNVHQ4EFgQUxFQLblR6RIxlVmtRQ6qP7higrkMwHwYDVR0j
    BBgwFoAUxFQLblR6RIxlVmtRQ6qP7higrkMwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAhgQ4D7VhW+38xj0Nf4r3N2/fI+jHft/vrOPLJH3mh14K
    r0Kd5oSnK2F9n5Vd+JaCcjeh3vmcXaNS1b4M83KF3yJDAUMzMXHExiX+tg8F2uhA
    xs0cU/hcXybdOx45vZ+5YQPKuOu84uXOtI6vrDjBvwtV1OVJAeKXGQOApZo8xSfE
    9AQzzCEbOUyJof2mr1IbNFBBoKfBgEaOiXLLIN6siZECOUm+KPPOU3OWCsVDXzvC
    zrbdWExEh2PGveN7b8Q0jqrPXDXw+MfIeswQYEf1fjl+SxhF6DhKQkpVlrfmMFmg
    oC0qC/q88KPPbxazGCOz+C54IumNnvoX99AsP/rRdA==
    -----END CERTIFICATE-----
