 
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: dallas-sriov-vfio-dell00-server-profile-dell-640
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_netdevice"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/dallas-sriov-netdevice-server_profile_dell_640: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
          - ens2f1#0-3
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: dallas-sriov-a-vfio-dell00-server-profile-dell-640
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/dallas-sriov-vfio-server_profile_dell_640: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
          - ens2f1#4-7
    
