---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: phoenixqa6
  namespace: phoenixqa6
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: phoenixqa6
    version: v1beta1
  clusterName: phoenixqa6
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: phoenixqa6
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: phoenixqa6
  namespace: phoenixqa6
spec:
  apiVIP: 9.37.195.53
  ingressVIP: 9.37.195.54
  clusterDeploymentRef:
    name: phoenixqa6
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: "vran-ocp-v4.9.9-master-4-ocp49-2"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM9jEkl/mHFdGfnGV5a+nxt2We54F59VCP7r/cvNn/Vp11/WkQWfWYtSkN4a+hiu4LnrcKUuy6Hqpce75sSxFG1XYzMHq0ZSvHooFs9ZxDhZ9lyDk5Wr9/MRD3qTD8Hga1z4xP4mdLJs2/7J4ubvMluE4DSrv1odhh++zTPF0da4WzfDxfFFeL4PAirQfijSZUw35cyRh3BA5JLcM8kza/3RiXmWUdAvld4gu2oTDjJqE1uplC++WH/SJi38Z6WjddvrGVwMbizGILkO40OGqndwNY7woozp+3TyZbWFionsUbafTxkJudnfADC44SDVZPGQDK0erlGjskcRfX29ft"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: phoenixqa6
  namespace: phoenixqa6
spec:
  clusterName: phoenixqa6
  clusterNamespace: phoenixqa6
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: phoenixqa6
  namespace: phoenixqa6
  
spec:
  clusterRef:
    name: phoenixqa6
    namespace: phoenixqa6
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: phoenixqa6
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM9jEkl/mHFdGfnGV5a+nxt2We54F59VCP7r/cvNn/Vp11/WkQWfWYtSkN4a+hiu4LnrcKUuy6Hqpce75sSxFG1XYzMHq0ZSvHooFs9ZxDhZ9lyDk5Wr9/MRD3qTD8Hga1z4xP4mdLJs2/7J4ubvMluE4DSrv1odhh++zTPF0da4WzfDxfFFeL4PAirQfijSZUw35cyRh3BA5JLcM8kza/3RiXmWUdAvld4gu2oTDjJqE1uplC++WH/SJi38Z6WjddvrGVwMbizGILkO40OGqndwNY7woozp+3TyZbWFionsUbafTxkJudnfADC44SDVZPGQDK0erlGjskcRfX29ft"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-80-std"
  namespace: phoenixqa6
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa6"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa6-master-dell-80-std-bmh-secret
  bootMACAddress: E4:43:4B:F0:E3:00
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-81-std"
  namespace: phoenixqa6
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa6"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa6-master-dell-81-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:01:10
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-82-std"
  namespace: phoenixqa6
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa6"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa6-master-dell-82-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:A4:E0
  automatedCleaningMode: disabled
  online: true
---
