---
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: ran-cu-dallas-server-profile-dell-640-pao-profile-dell-640
spec:
  cpu:
    isolated: "4-38,5-39"
    reserved: "0-2,1-3"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 50
      node: 0 
    - size: "1G"
      count: 50
      node: 1 
  numa:
    topologyPolicy: restricted
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  nodeSelector:
    node-role.kubernetes.io/master: ""

