apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-node-42-sno2"
  namespace: "master-node-42-sno2"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.9.9-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDl8ffdUj9qgUqXaP9uF+6DD3C4qk0WJ7tmDC7S4HtlllA4tf+z6Gb9w0Fzr5crv0SqDpxjXhmu0VO/myRv2kVHstu+3yBeevkfEjbTc18nhwH3t99QvMo3k/Cp7pf1SG3Y57SCbMKRLmu3Y2i5orb6mlDcbqrRi52A74r8P1VwcmOFn3+SVnXWHVz5NUd4o82BXfqDeJYKPu9qMCVW052eT38A7SWE6fA7o0zVxv3VALxYUx3SW/NZlUYNFriQfhyU/2nlCFFrHvQUSfQueR9T1nWQIKlNsdzz/UTfQscnE6Kcsv6CQUh+e6XZolwv/5Z4vG9gjXHkJfXKcf7svqNZ"
  clusters:
  - clusterName: "master-node-42-sno2"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-node-42-sno2"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/26
    nodes:
       - hostName: "master-node-42-sno2"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-node-42-sno2-master-node-42-sno2-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
