---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
  name: label-sno-6-job
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/node
              echo ""
              echo -n "Add node labels"
              until oc wait --selector=node-role.kubernetes.io/ran-cu-banashankari-supermicro00='',kubernetes.io/hostname=sno-6.vran.ibm.com --for=condition=ready nodes
              do
                echo -n "...still waiting for applying labels"
                oc label node sno-6.vran.ibm.com ran.openshift.io/banashankari-local-storage-supermicro00=""
                oc label node sno-6.vran.ibm.com node-role.kubernetes.io/ran-cu-banashankari-supermicro00=""
                oc label node sno-6.vran.ibm.com ran.openshift.io/ocpvirt=""
                oc label node sno-6.vran.ibm.com ran.openshift.io/sriov=""
                oc label node sno-6.vran.ibm.com feature.node.kubernetes.io/network-sriov.capable=true
                oc label node sno-6.vran.ibm.com ran.openshift.io/banashankari-sriov-netdevice-supermicro00=""

                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: nodes-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
