---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: combined-ran
  namespace: poc-cu2
spec:
  # The argocd project the application belongs to
  project: default
  destination:
    server: https://api.poc-cu2.samsung.com:6443
  # Source of the application manifests
  source:
    repoURL: https://github.com/kirankumarhn82/vran-manifests.git
    path: clusters/poc-cu2.samsung.com
    targetRevision: main    
    directory:
      recurse: false
  # Sync policy
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      # (equivalent to 'kubectl apply --validate=true')
      - Validate=false
      - CreateNamespace=true
    retry:
      # unlimited if less than 0
      limit: -1
      backoff:
        # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        duration: 5s
        # a factor to multiply the base duration after each failed retry
        factor: 2
        # the maximum amount of time allowed for the backoff strategy
        maxDuration: 3m
