apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sam-raid0-xnf"
  namespace: "sam-raid0-xnf"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.9.9-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6v1jXIPu6r+KUMboE4nzO2/ZDUBzTQ5ZhhnCGDwPSQWzk5Q9YAoMbPVG3surhIH+RZxYH0R+atufQWIdBHCPgJtRa5GY7RijPeVCmUvGYAHvCejqAPRfTlcimdLsEVaX2mF5wevMWr0TERqVjq5vGNRSlw5Ae8vo12ZTOI80gv+ZfohdzX+tloGcrJNWOcgSiMMBUMxXZiLShGQwH1zSetp3XeFGLdHrSjgs13sDyKFxJ64NnqpD89UAKGSlHNXoxLL6z5RGnJl+iiLS/p0DFqb+kHjm+mw12vPOWJR5H1igBVKTDtbSgYGJmwzGd/toVvM9g0+ZOYHUnRQys8Ufz"
  clusters:
  - clusterName: "sam-raid0-xnf"
    clusterType: "sno"
    clusterProfile: "cu"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "sam-raid0-xnf"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "sam-raid0-xnf.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "sam-raid0-xnf-sam-raid0-xnf-bmh-secret"
         bootMACAddress: "E4:43:4B:F0:E3:00"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F0:E3:00"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F0:E3:00"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
