---
apiVersion: v1
data:
  password: Z2hwX0R2eGJTZUpxdXl4VUxFc2plQ29xWVBRRTE3dXpNbzQ4RDF4MA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2tpcmFua3VtYXJobjgyL3ZyYW4tbWFuaWZlc3RzLmdpdA==
  username: a2lyYW5rdW1hcmhuODI=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-kirankumarhn82-vran-manifests
  namespace: master-dell-44-qa17a
type: Opaque