 
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: banglore-sriov-vfio-dell00-dell00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_netdevice"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/banglore-sriov-netdevice-dell00: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens2f1#0-7
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: banglore-sriov-a-vfio-dell00-dell00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/banglore-sriov-vfio-dell00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens2f1#8-15
    
