---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: phoenixqa7
  namespace: phoenixqa7
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: phoenixqa7
    version: v1beta1
  clusterName: phoenixqa7
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: phoenixqa7
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: phoenixqa7
  namespace: phoenixqa7
spec:
  apiVIP: 9.37.195.53
  ingressVIP: 9.37.195.54
  clusterDeploymentRef:
    name: phoenixqa7
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: "vran-ocp-v4.9.9-master-4-ocp49-2"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI4hxuC2AoWEXfh6ubXGaiffhvDQVJY1Brav9IGfzI8+Mn/mQwjSkxOrGtgFESawoIyIpqhpXO6eZhH1Sn54aLZME8WaCEcSghCQ88ZOmP/+nzAuQk2BKeXKCEsgWf6xX8a688G8e/ER9gZ1zp5mzYokKMXhOCRwPvLSx+NO04F2nASjGcmh7Vv64VuBtYaTzn02JglaWg/Xrg9PRGz3ms7TzoQcnLuV8ALVNUgUWSrLDJmCnB1HlB0S/PWh/2mHYdhiFNxXHWiijF72Isl6TrzKDo3fEK4/iB1PFoGLPfpy6jUnoDliYbB8b2wWPfJq6uGjzh6XY5hKlR/DLCrnpV"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: phoenixqa7
  namespace: phoenixqa7
spec:
  clusterName: phoenixqa7
  clusterNamespace: phoenixqa7
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: phoenixqa7
  namespace: phoenixqa7
  
spec:
  clusterRef:
    name: phoenixqa7
    namespace: phoenixqa7
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: phoenixqa7
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI4hxuC2AoWEXfh6ubXGaiffhvDQVJY1Brav9IGfzI8+Mn/mQwjSkxOrGtgFESawoIyIpqhpXO6eZhH1Sn54aLZME8WaCEcSghCQ88ZOmP/+nzAuQk2BKeXKCEsgWf6xX8a688G8e/ER9gZ1zp5mzYokKMXhOCRwPvLSx+NO04F2nASjGcmh7Vv64VuBtYaTzn02JglaWg/Xrg9PRGz3ms7TzoQcnLuV8ALVNUgUWSrLDJmCnB1HlB0S/PWh/2mHYdhiFNxXHWiijF72Isl6TrzKDo3fEK4/iB1PFoGLPfpy6jUnoDliYbB8b2wWPfJq6uGjzh6XY5hKlR/DLCrnpV"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-80-std"
  namespace: phoenixqa7
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa7"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa7-master-dell-80-std-bmh-secret
  bootMACAddress: E4:43:4B:F0:E3:00
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-81-std"
  namespace: phoenixqa7
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa7"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa7-master-dell-81-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:01:10
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-82-std"
  namespace: phoenixqa7
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa7"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa7-master-dell-82-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:A4:E0
  automatedCleaningMode: disabled
  online: true
---
