apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno-cluster-1.sdn.ibm.corp-gitops
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
#    namespace: test-sno-siteconfig
  project: default
  source:
    path: clusters/sno-cluster-1.sdn.ibm.corp/ztp/gitops
    repoURL: https://github.com/kirankumarhn82/vran-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
