---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-dallas-dell00

commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  


resources:
  - 00-label-wait-job-dallas-sam-server-auto-mc.yaml

#  - 00-mcp-wait-job-dallas-sam-server-auto-mc.yaml  
  - 01-mc-lvm-ran-cu-dallas-dell00.yaml