kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oc-image-registry-pvc
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ABCD
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem