apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-master-4-ocp48-qa10.vran.ibm.com
  namespace: openshift-gitops
spec: 
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/master-4-ocp48-qa10.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/kirankumarhn82/vran-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true