apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "stgautoissue"
  namespace: "stgautoissue"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.9.9-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqRI98o0VMEY88RaNQZS2pUQMVMtPBBtCLZeY/DnCZIL++ep/5H/oL16afj/UYT6r98whCRa1NyLzUoURLcp1cwyGaNTSPr0yVeQrO1HYHAZM7VF++9rBPVYPYQyZtHJ3MVe5fqMIx+/v7g4ueiz+Td9fmSRtsk3VrLF6XVPx+9NHRzRdjezsQsPiMjh3hZDqxaAnaZir7YImVvOQk5c/Sm+uJlSsra0PZ87TX7Q24D04+x5ldsG5+Q/AqvuWn9Kv/IOZOOaF29sknxStWGyYbjFIfeKzCQhXR8NAONWKO+5UlcqJz+aShYD2d39MyGD6M10YPgIlSM69/9w2NOBEf"
  clusters:
  - clusterName: "stgautoissue"
    clusterType: "standard"
    clusterProfile: "du"
    numMasters: 3
    numWorkers: 2
    clusterLabels:
      common: true
      sites : "stgautoissue"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    apiVIP: 9.37.195.53
    ingressVIP: 9.37.195.54
    nodes:
       - hostName: "ibm-lab-std1.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "stgautoissue-ibm-lab-std1-bmh-secret"
         bootMACAddress: "E4:43:4B:F0:E3:00"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F0:E3:00"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F0:E3:00"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "ibm-lab-std2.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "stgautoissue-ibm-lab-std2-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:01:10"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:01:10"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:01:10"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "ibm-lab-std3.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "stgautoissue-ibm-lab-std3-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:A4:E0"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:A4:E0"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:A4:E0"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
