apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "stgautoissue"
  namespace: "stgautoissue"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.9.9-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDc40ogBHFlTp+jU53ggin2YpykA31/8qN2PrG78N9wW9ls43YpJzHZ8D+aHYNrGRsuN2PzraBy3T+bJQy3EXU4qa9heb2/UBgkwbbnqyX/MnEy9m/DrjeO9o3zjOO3QfqbvDHYAqW6iWg9lf3ZdJJMt8FL3XNvhgNhkLG5lvrLKWLqTE3M+V16n8OZz8ZioE1Cnm9jYdA329v21zxK9AevpMEJIcbEPkcPokRTkl8UbdmEu/Elr+4OnHdbgVPHmU1w8KWlRQR2L1QWaV1ZPxzEZ/3Rz4Pd5y5YAQNdsPfbKqrBRR5PNYv6MAin5HzQ8gzAVKAl+IQGguFsoQsVKdeZ"
  clusters:
  - clusterName: "stgautoissue"
    clusterType: "standard"
    clusterProfile: "du"
    numMasters: 3
    numWorkers: 2
    clusterLabels:
      common: true
      sites : "stgautoissue"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    apiVIP: 9.37.195.53
    ingressVIP: 9.37.195.54
    nodes:
       - hostName: "ibm-lab-std2.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "stgautoissue-ibm-lab-std2-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:01:10"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:01:10"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:01:10"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "ibm-lab-std3.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "stgautoissue-ibm-lab-std3-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:A4:E0"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:A4:E0"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:A4:E0"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "ibm-lab-std4.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.83/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "stgautoissue-ibm-lab-std4-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:A0:E0"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:A0:E0"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:A0:E0"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
